name: Publish Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release Type'
        default: 'feature'
        required: false
        type: choice
        options:
          - 'major'
          - 'feature'
          - 'patch'
      publish:
        description: 'Publish on Workshop'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      workshop-id:
        description: 'Workshop Identifier'
        required: false
        default: '3338630543'
        type: string

jobs:
  release:
    name: "Publish Release"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Checkout Tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch --prune --unshallow --tags

        # Get the latest tag from git
        # Tag is used as the last version
      - name: Get Version
        id: project
        run: |
          echo "last-version=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

        # Move files relevant for the steam release into a separate folder
        # Remove all other folders and files that should not be in the release
      - name: Clean Repository
        run: |
          mkdir ../steam-release
          mv STEAM_PAGE.bbcode ../steam-release/STEAM_PAGE.bbcode
          mv script/create-release-vdf.sh ../steam-release/create-release-vdf.sh
          rm -rf .git/
          rm -rf .github/
          rm -rf docs/
          rm -rf script/
          rm -f .gitattributes
          rm -f .gitignore
          rm -f vic3-tiger.conf
          rm -f README.md

        # Create mod metadata for the steam release
        # Uses STEAM_PAGE.bbcode to update steam description
        # Report: Generated metadata
      - name: Create Workshop Metadata
        if: ${{ inputs.publish == 'true' }}
        id: metadata
        shell: bash
        run: |
          ../steam-release/create-release-vdf.sh ${{ github.workspace }} ../steam-release/STEAM_PAGE.bbcode "${{ inputs.workshop-id }}"
          mv workshop.vdf ../steam-release/workshop.vdf
          echo "vdf=$(realpath ../steam-release/workshop.vdf)" >> "$GITHUB_OUTPUT"
          echo "# Workflow Metadata" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "$(cat < ../steam-release/workshop.vdf)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Setup SteamCMD
        if: ${{ inputs.publish == 'true' }}
        uses: CyberAndrii/setup-steamcmd@v1

        # Publish to steam workshop
        # Uses generated metadata and configured workshop user
      - name: Publish to Workshop
        if: ${{ inputs.publish == 'true' }}
        shell: bash
        run: |
          steamcmd +login ${{ secrets.WORKSHOP_USERNAME }} ${{ secrets.WORKSHOP_PASSWORD }} +workshop_build_item ${{ steps.metadata.outputs.vdf }} +quit
